CREATE DATABASE QLPM
GO

USE QLPM
GO

--Account
CREATE TABLE Account
(
	TenDangNhap CHAR(255) PRIMARY KEY,
	TenHienThi NVARCHAR(255) NOT NULL,
	MatKhau CHAR(1000) NOT NULL,
	Loai INT --0:nhân viên || 1: admin
)
GO

--Bệnh nhân
CREATE TABLE BenhNhan
(
	MaBenhNhan NVARCHAR(10) PRIMARY KEY,
	HoLot NVARCHAR(255) NOT NULL,
	TenBN NVARCHAR(255) NOT NULL,
	GioiTinh NVARCHAR(3) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(255),
	LienHe NVARCHAR(255),
	GhiChu NVARCHAR(1000)
)
GO

--Bác sĩ
CREATE TABLE BacSi
(
	MaBacSi NVARCHAR(10) PRIMARY KEY,
	HoLot NVARCHAR(255) NOT NULL,
	TenNV NVARCHAR(255) NOT NULL
)
GO

--Thuốc
CREATE TABLE Thuoc
(
	MaThuoc INT IDENTITY PRIMARY KEY,
	TenThuoc NVARCHAR(30) NOT NULL,
	DonVi int NOT NULL, --1: Viên ||2: Gói||3: ống
	NSX DATE NOT NULL,
	HSD DATE NOT NULL,
	GiaThuoc INT NOT NULL
)
GO

--Phiếu khám
CREATE TABLE PhieuKham
(
	MaPhieuKham INT IDENTITY PRIMARY KEY,
	MaBenhNhan NVARCHAR(10) NOT NULL,
	NgayKham DATETIME NOT NULL,
	TrieuChung NVARCHAR(255) NOT NULL,
	ChuanDoan NVARCHAR(255) NOT NULL,
	MaBS NVARCHAR(10) NOT NULL,
	TienKham INT NOT NULL DEFAULT 30000,

	FOREIGN KEY(MaBenhNhan) REFERENCES dbo.BenhNhan(MaBenhNhan),
	FOREIGN KEY(MaBS) REFERENCES dbo.BacSi(MaBacSi)
)
--Đơn thuốc
CREATE TABLE DonThuoc
(
	MaDon INT IDENTITY PRIMARY KEY,
	MaBenhNhan NVARCHAR(10) NOT NULL,
	NgayIn DATETIME NOT NULL,
	MaBS NVARCHAR(10) NOT NULL,
	TongTien INT NOT NULL,

	FOREIGN KEY(MaBenhNhan) REFERENCES dbo.BenhNhan(MaBenhNhan),
	FOREIGN KEY(MaBS) REFERENCES dbo.BacSi(MaBacSi)
)
GO
--Chi tiết đơn thuốc
CREATE TABLE ChiTietDonThuoc
(
	MaDon INT NOT NULL,
	MaThuoc INT NOT NULL,
	CachDung NVARCHAR(30) NOT NULL,
	SLSang INT DEFAULT 0,
	SLTrua INT DEFAULT 0,
	SLChieu INT DEFAULT 0,
	SLToi INT DEFAULT 0,
	Tong INT DEFAULT 0,
	ThanhTien INT NOT NULL,

	PRIMARY KEY(MaDon,MaThuoc),
	FOREIGN KEY(MaThuoc) REFERENCES dbo.Thuoc(MaThuoc),
	FOREIGN KEY(MaDon) REFERENCES dbo.DonThuoc(MaDon)
)
GO

--Hóa đơn
CREATE TABLE HoaDon
(
	id INT IDENTITY PRIMARY KEY,
	MaPK INT NOT NULL,
	MaDT INT NOT NULL,

	FOREIGN KEY(MaPK) REFERENCES dbo.PhieuKham(MaPhieuKham),
	FOREIGN KEY(MaDT) REFERENCES dbo.DonThuoc(MaDon),
)
GO